### ISSUE TITLE
Causes the com.apple.desktoppicture folder to grow rapidly

### ISSUE THREAD

**Issue by errorfg** [KYDronePilot/SpaceEye#31]
com.apple.desktoppicture caches full-sized desktop images. After two months of use, my com.apple.desktoppicture folder has grown to 34.5G. Can you add a function to the software to clear the cache of the com.apple.desktoppicture folder?
![CleanShot 2021-08-07 at 21 01 41](https://user-images.githubusercontent.com/18473413/128601209-c06aa079-b976-4c35-b2e4-8993dc097c5a.png)

**Comment by KYDronePilot** [comment]
Unfortunately, this is something we cannot fix at this time. macOS doesn't allow apps to access that folder.

The folder can be quickly cleared manually by running the following command in Terminal:

```bash
rm /private/var/folders/*/*/C/com.apple.desktoppicture/*.png
```
