### ISSUE TITLE
Failed to download image.

### ISSUE THREAD

**Issue by bruseful** [KYDronePilot/SpaceEye#56]
Failed to download the thumbnail (and likely the full sized image) for this view.

After update to W11 Pro Insider Build 25262.

**Comment by cheeseandjamsandwich** [comment]
SpaceEye fails to work any more for me too. :-(
Is it the certificate problem as noted in #47 ?

I really, really hope @KYDronePilot can find a little bit of time to fix this awesome software!
I install it on every machine i have!

One bit of luck for me, is that when it failed, it was almost midday where i am and Himawari-8 was mostly fully lit, with Australia mostly cloud-free... so i'm left with a beautiful full-disk as my wallpaper at least...

**Comment by dzzhyk** [comment]
> same problem for me too, I really hope someone could fix this XD.

Update: 2022-12-25 16:29:34 it WORKS perfectly

**Comment by KYDronePilot** [comment]
As mentioned in #47, fixed by switching the imagery CDN to a different SSL certificate authority. Please let me know if this issue ever comes up again!
