### ISSUE TITLE
Image download fails.

### ISSUE THREAD

**Issue by gerrith** [KYDronePilot/SpaceEye#65]
Image download fails.

![image](https://github.com/KYDronePilot/SpaceEye/assets/2377224/31150080-50b2-40bd-a535-f65e73ae4eed)

**Comment by RichL2004** [comment]
Agreed. Showing errors on download and no updated images for about a week now.

**Comment by RichL2004** [comment]
Further inspection indicates the images are downloading from "you" but the images are still the same image form several weeks ago...

**Comment by KYDronePilot** [comment]
Issue should be fixed now. @RichL2004 and @mnrocha-ufv please let me know if you encounter any other problems!

**Comment by mnrocha-ufv** [comment]
Now it's working! Thanks, Michael!

**Comment by RichL2004** [comment]
All appears to be working now. Thank you very much Michael.....
